# Supported funding platforms

github: [ADA-XiaoYao]            # GitHub Sponsors username
patreon: ""                       # Patreon username, leave empty if none
open_collective: ""                # Open Collective username, leave empty if none
ko_fi: ""                          # Ko-fi username, leave empty if none
tidelift: ""                       # Tidelift platform/package name, leave empty if none
community_bridge: ""               # Community Bridge project name, leave empty if none
liberapay: ""                       # Liberapay username, leave empty if none
issuehunt: ""                      # IssueHunt username, leave empty if none
lfx_crowdfunding: ""               # LFX Crowdfunding project name, leave empty if none
polar: ""                          # Polar username, leave empty if none
buy_me_a_coffee: ""                # Buy Me a Coffee username, leave empty if none
thanks_dev: ""                      # thanks.dev username, leave empty if none
custom: []                         # Custom sponsorship links, e.g., ['https://example.com/donate']
